name: thesis-engagenet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - imbalanced-learn
  - pytest
  - pip
